"""
Workspace sync — syncs OpenClaw's "brain" into IDE-native rule files.

Usage:
    openclaw workspace sync --editors cursor
    openclaw workspace sync --editors cursor,vscode
"""

from __future__ import annotations

import logging
import time
from pathlib import Path

from openclaw.config import OpenClawConfig
from openclaw.skills import SkillRegistry

logger = logging.getLogger("openclaw.workspace")

HEADER = """\
# ─── Auto-generated by OpenClaw workspace sync ───
# Last synced: {timestamp}
# Do not edit manually — re-run `openclaw workspace sync` to update.
#
"""


def sync_to_editors(config: OpenClawConfig, editors: list[str]) -> None:
    """Write OpenClaw context into IDE-specific rule files."""
    workspace = config.resolved_workspace

    # Load skills + context
    skills = SkillRegistry()
    skills.load_bundled()
    skills.load_workspace(workspace)

    # Gather context sources
    brain = _build_brain(workspace, skills)

    for editor in editors:
        editor = editor.strip().lower()
        if editor == "cursor":
            _sync_cursor(workspace, brain)
        elif editor == "vscode":
            _sync_vscode(workspace, brain)
        else:
            logger.warning("Unknown editor: %s (supported: cursor, vscode)", editor)


def _build_brain(workspace: Path, skills: SkillRegistry) -> str:
    """Assemble the full OpenClaw 'brain' as markdown."""
    sections: list[str] = []

    # Identity
    for name in ("AGENTS.md", "SOUL.md", "IDENTITY.md"):
        f = workspace / name
        if f.exists():
            sections.append(f"## {name}\n\n{f.read_text(encoding='utf-8')}")

    # Progress
    progress = workspace / "PROGRESS.md"
    if progress.exists():
        sections.append(f"## Current Progress\n\n{progress.read_text(encoding='utf-8')}")

    # Skills
    for skill in skills.all():
        sections.append(
            f"## Skill: {skill.meta.name}\n\n"
            f"*{skill.meta.description}*\n\n"
            f"{skill.textbook}"
        )

    return "\n\n---\n\n".join(sections)


def _sync_cursor(workspace: Path, brain: str) -> None:
    """Write to .cursorrules and .cursor/rules/openclaw.mdc"""
    timestamp = time.strftime("%Y-%m-%d %H:%M:%S")
    content = HEADER.format(timestamp=timestamp) + brain

    # .cursorrules (legacy single-file format)
    cursorrules = workspace / ".cursorrules"
    cursorrules.write_text(content, encoding="utf-8")
    logger.info("Synced → %s", cursorrules)

    # .cursor/rules/openclaw.mdc (new structured format)
    mdc_dir = workspace / ".cursor" / "rules"
    mdc_dir.mkdir(parents=True, exist_ok=True)
    mdc_file = mdc_dir / "openclaw.mdc"
    mdc_content = (
        "---\n"
        "description: OpenClaw agent context and skills\n"
        "globs: [\"**/*\"]\n"
        "alwaysApply: true\n"
        "---\n\n"
        + content
    )
    mdc_file.write_text(mdc_content, encoding="utf-8")
    logger.info("Synced → %s", mdc_file)


def _sync_vscode(workspace: Path, brain: str) -> None:
    """Write to .vscode/openclaw-context.md (picked up by Copilot instructions)."""
    timestamp = time.strftime("%Y-%m-%d %H:%M:%S")
    content = HEADER.format(timestamp=timestamp) + brain

    vscode_dir = workspace / ".vscode"
    vscode_dir.mkdir(parents=True, exist_ok=True)
    out = vscode_dir / "openclaw-context.md"
    out.write_text(content, encoding="utf-8")
    logger.info("Synced → %s", out)

    # Also write to .github/copilot-instructions.md if .github/ exists
    github_dir = workspace / ".github"
    if github_dir.is_dir():
        copilot_file = github_dir / "copilot-instructions.md"
        copilot_file.write_text(content, encoding="utf-8")
        logger.info("Synced → %s", copilot_file)
