version: '3.5'

services:
  milvus:
    container_name: milvus-standalone
    image: milvusdb/milvus:v2.4.0
    command: ["milvus", "run", "standalone"]
    security_opt:
      - seccomp:unconfined
    environment:
      - ETCD_USE_EMBED=true
      - ETCD_DATA_DIR=/var/lib/milvus/etcd
      - COMMON_STORAGETYPE=local
    volumes:
      - milvus_data:/var/lib/milvus
    ports:
      - "19530:19530"
      - "9091:9091"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9091/healthz"]
      interval: 30s
      start_period: 90s
      timeout: 20s
      retries: 3
    networks:
      - default
  
  # for dashboard of the milvus
  attu:
    container_name: milvus-attu
    image: zilliz/attu:v2.4.0
    environment:
      - MILVUS_URL=milvus-standalone:19530  # Matches the container_name of your milvus service
    ports:
      - "0.0.0.0:8000:3000"                 # Explicitly binds port 8000 to your machine
    depends_on:
      - milvus
    networks:
      - default
    
volumes:
  milvus_data:

networks:
  default:
    name: milvus