#!/usr/bin/env python3
"""
clawsync_init.py — ClawSync Infrastructure Script
===================================================
Bootstraps the Global Context Bridge for a project:
  • Creates .openclaw/ with global_state.md & active_task.md
  • Writes .cursorrules pointing to shared context
  • Patches .vscode/settings.json with Copilot instructions
  • Writes AGENTS.md (the project "Soul" for Antigravity)

Cross-platform: works on Windows, macOS, and Linux.
"""

from __future__ import annotations

import json
import os
import platform
import sys
from datetime import datetime
from pathlib import Path
from typing import Optional


# ────────────────────────────────────────────────────────────────────────────
# Constants
# ────────────────────────────────────────────────────────────────────────────

OPENCLAW_DIR = ".openclaw"
GLOBAL_STATE_FILE = "global_state.md"
ACTIVE_TASK_FILE = "active_task.md"
CURSORRULES_FILE = ".cursorrules"
VSCODE_DIR = ".vscode"
VSCODE_SETTINGS_FILE = "settings.json"
AGENTS_FILE = "AGENTS.md"

TIMESTAMP = datetime.now().strftime("%Y-%m-%d %H:%M:%S")
OS_NAME = platform.system()  # "Windows" | "Darwin" | "Linux"


# ────────────────────────────────────────────────────────────────────────────
# Helpers
# ────────────────────────────────────────────────────────────────────────────

def resolve_project_root(path: Optional[str] = None) -> Path:
    """Return the absolute project root (defaults to CWD)."""
    root = Path(path).resolve() if path else Path.cwd()
    if not root.is_dir():
        print(f"[ERROR] '{root}' is not a valid directory.")
        sys.exit(1)
    return root


def safe_write(file_path: Path, content: str, overwrite: bool = False) -> None:
    """Write content to a file; skip if exists unless overwrite=True."""
    if file_path.exists() and not overwrite:
        print(f"  [SKIP]  {file_path} already exists.")
        return
    file_path.parent.mkdir(parents=True, exist_ok=True)
    file_path.write_text(content, encoding="utf-8")
    print(f"  [OK]    {file_path}")


def patch_json_file(file_path: Path, updates: dict) -> None:
    """Merge `updates` into an existing (or new) JSON file."""
    file_path.parent.mkdir(parents=True, exist_ok=True)
    existing: dict = {}
    if file_path.exists():
        try:
            existing = json.loads(file_path.read_text(encoding="utf-8"))
        except json.JSONDecodeError:
            print(f"  [WARN]  {file_path} has invalid JSON — overwriting.")
    existing.update(updates)
    file_path.write_text(json.dumps(existing, indent=2), encoding="utf-8")
    print(f"  [OK]    {file_path}")


# ────────────────────────────────────────────────────────────────────────────
# File-content templates
# ────────────────────────────────────────────────────────────────────────────

def _global_state_content(project_name: str) -> str:
    return f"""\
# 🌐 Global Project State — {project_name}

> **Source of Truth** for all agents and IDEs (Cursor · VS Code · Antigravity).
> Managed by ClawSync. Do **not** edit manually while agents are active.

---

## Project
- **Name**: {project_name}
- **Root**: (populated by ClawSync at runtime)
- **Initialised**: {TIMESTAMP}
- **OS**: {OS_NAME}

---

## Agent History (append-only log)

<!-- ClawSync appends entries below this line. Most recent = bottom. -->

| Timestamp | Agent | Status Update |
|-----------|-------|---------------|
| {TIMESTAMP} | ClawSync-Init | Project registered. Global Context Bridge activated. |

---

## Shared Decisions & Context

_Add architectural decisions, API contracts, or cross-IDE context here._
"""


def _active_task_content(project_name: str) -> str:
    return f"""\
# 🎯 Active Task — {project_name}

> Updated by the currently active agent. All other agents should treat this
> as read-only until the lock is released.

---

## Current Focus

- **Agent**:        _none_
- **Task**:         _none_
- **Started**:      {TIMESTAMP}
- **Status**:       `idle`

---

## Subtasks

- [ ] _No active task_

---

## Blockers

_None._

---

## Last Sync

`{TIMESTAMP}` · initialised by ClawSync-Init
"""


def _cursorrules_content(state_rel: str, task_rel: str) -> str:
    return f"""\
# .cursorrules — Generated by ClawSync
# These rules are automatically read by Cursor AI on every chat turn.

## 🔗 Global Context Bridge — MANDATORY RULES

This project uses ClawSync. You MUST follow ALL rules below on EVERY response.

### ⚠️ REQUIRED — Before Every Response
1. Silently read `{state_rel}` to understand full project history.
2. Silently read `{task_rel}` to see who owns the current task.

### ⚠️ REQUIRED — After Every Code Change
After making ANY code edit, function addition, refactor, or fix, you MUST
immediately call the ClawSync MCP tool:

  update_context("Cursor AI", "<one-line description of exactly what you changed>")

Do NOT skip this step. Do NOT wait to be asked. Write to `{state_rel}` automatically.
If the MCP tool is unavailable, manually append a row to the Agent History table
in `{state_rel}` using this format:
  | YYYY-MM-DD HH:MM:SS | Cursor AI | <what you changed> |

### ⚠️ REQUIRED — Task Ownership
- Update `{task_rel}` when you START a task (set Agent: Cursor AI, Status: in-progress).
- Update `{task_rel}` when you FINISH a task (set Status: done).
- Never overwrite history rows — only append.
- If another agent owns the active task, ask the user before proceeding.

### Identity
You are **Cursor AI** inside the ClawSync ecosystem. Antigravity and GitHub
Copilot share the same state files. Your updates are their context.
"""


def _vscode_settings_patch(state_rel: str, task_rel: str) -> dict:
    instructions = (
        f"CLAWSYNC GLOBAL CONTEXT BRIDGE — MANDATORY RULES. "
        f"(1) BEFORE every response: silently read '{state_rel}' and '{task_rel}'. "
        f"(2) AFTER every code change, function edit, or refactor: you MUST call the "
        f"ClawSync MCP tool update_context('GitHub Copilot', '<what you changed>'). "
        f"Do NOT skip this. Do NOT wait to be asked. This is required on every edit. "
        f"If the MCP tool is unavailable, manually append a row to the Agent History "
        f"table in '{state_rel}' using format: "
        f"| YYYY-MM-DD HH:MM:SS | GitHub Copilot | <description> |. "
        f"(3) Update '{task_rel}' when you start or finish a task. "
        f"(4) Never delete or overwrite existing history rows — only append. "
        f"You are GitHub Copilot inside the ClawSync ecosystem. "
        f"Cursor AI and Antigravity share these same files."
    )
    return {
        "github.copilot.chat.instructions": instructions,
        "github.copilot.chat.localeOverride": "en",
    }


def _agents_md_content(project_name: str, state_rel: str, task_rel: str) -> str:
    return f"""\
# AGENTS.md — Project Soul for Antigravity
# ==========================================
# Antigravity reads this file at the start of every session.

## 🧠 Who You Are

You are an **Antigravity agent** operating inside the **ClawSync Global
Context Bridge** for project **{project_name}**.

---

## 📁 ClawSync State Files (your ground truth)

| File | Purpose |
|------|--------|
| `{state_rel}` | Full project history, decisions, cross-IDE knowledge |
| `{task_rel}` | The single active task; who owns it and what's in progress |

---

## ⚠️ MANDATORY Behaviours — Follow on EVERY Session

1. **On session start**: Read both files above silently before doing anything.
2. **Before any code change**: Check `{task_rel}` — is there a conflicting
   active task from another agent? If yes, ask the user.
3. **After EVERY code change, edit, or decision**: IMMEDIATELY append a row
   to the Agent History table in `{state_rel}`. Do NOT skip this.
   Format:
   ```
   | YYYY-MM-DD HH:MM:SS | Antigravity | <one-line summary of exactly what you changed> |
   ```
4. **Update `{task_rel}`** when you START a task (Status: in-progress) and
   when you FINISH (Status: done).
5. **Never overwrite** existing history rows — only append.

---

## 🌐 Ecosystem Partners

- **Cursor AI**  — reads `.cursorrules` → same state files
- **GitHub Copilot** → reads VS Code settings → same state files
- **Antigravity** → reads this file → same state files

All three agents share one truth. Conflicts are resolved by timestamp order
in `{state_rel}`.

---

## 🏗 Project Metadata

- **Initialised**: {TIMESTAMP}
- **Platform**: {OS_NAME}
- **ClawSync Version**: 1.0.0
- **MCP Server**: `clawsync_mcp.py` (FastMCP)

---

_ClawSync — "One Memory. Every IDE."_
"""


# ────────────────────────────────────────────────────────────────────────────
# Main init logic
# ────────────────────────────────────────────────────────────────────────────

def init_project(project_path: Optional[str] = None, overwrite: bool = False) -> Path:
    """
    Initialise the ClawSync Global Context Bridge for a project.

    Parameters
    ----------
    project_path : str | None
        Absolute or relative path to the project root. Defaults to CWD.
    overwrite : bool
        If True, regenerate files even if they already exist.

    Returns
    -------
    Path
        The resolved project root.
    """
    root = resolve_project_root(project_path)
    project_name = root.name

    print(f"\n╔══════════════════════════════════════════════════╗")
    print(f"║  ClawSync — Global Context Bridge Init           ║")
    print(f"╚══════════════════════════════════════════════════╝")
    print(f"  Project  : {project_name}")
    print(f"  Root     : {root}")
    print(f"  Platform : {OS_NAME}")
    print(f"  Time     : {TIMESTAMP}\n")

    openclaw_dir = root / OPENCLAW_DIR
    state_path = openclaw_dir / GLOBAL_STATE_FILE
    task_path = openclaw_dir / ACTIVE_TASK_FILE

    # Relative paths (used in file content)
    state_rel = f"{OPENCLAW_DIR}/{GLOBAL_STATE_FILE}"
    task_rel = f"{OPENCLAW_DIR}/{ACTIVE_TASK_FILE}"

    print("▸ Step 1 — Creating .openclaw/ directory")
    openclaw_dir.mkdir(exist_ok=True)
    print(f"  [OK]    {openclaw_dir}")

    print("\n▸ Step 2 — Writing shared state files")
    safe_write(state_path, _global_state_content(project_name), overwrite)
    safe_write(task_path, _active_task_content(project_name), overwrite)

    # .gitignore entry for registry (cross-platform safe)
    gitignore = root / ".gitignore"
    _ensure_gitignore_entry(gitignore, ".openclaw/registry.json")

    print("\n▸ Step 3 — Creating .cursorrules")
    cursorrules_path = root / CURSORRULES_FILE
    safe_write(
        cursorrules_path,
        _cursorrules_content(state_rel, task_rel),
        overwrite,
    )

    print("\n▸ Step 4 — Patching .vscode/settings.json")
    vscode_settings_path = root / VSCODE_DIR / VSCODE_SETTINGS_FILE
    patch_json_file(vscode_settings_path, _vscode_settings_patch(state_rel, task_rel))

    print(f"\n▸ Step 5 — Writing AGENTS.md")
    agents_path = root / AGENTS_FILE
    safe_write(
        agents_path,
        _agents_md_content(project_name, state_rel, task_rel),
        overwrite,
    )

    print("\n▸ Step 6 — Installing git post-commit hook")
    _install_git_hooks(root, state_rel)

    print(f"\n✅ ClawSync initialised successfully for '{project_name}'!\n")
    print(f"  Next: start the watcher daemon for real-time file-change sync:")
    print(f"  nohup python3 clawsync_watcher.py {root} > ~/.openclaw/watcher.log 2>&1 &\n")
    return root


def _ensure_gitignore_entry(gitignore: Path, entry: str) -> None:
    """Add `entry` to .gitignore if not already present."""
    lines: list[str] = []
    if gitignore.exists():
        lines = gitignore.read_text(encoding="utf-8").splitlines()
    if entry not in lines:
        lines.append(entry)
        gitignore.write_text("\n".join(lines) + "\n", encoding="utf-8")
        print(f"  [OK]    .gitignore updated with '{entry}'")


def _install_git_hooks(root: Path, state_rel: str) -> None:
    """
    Install a git post-commit hook that automatically appends the commit
    info to global_state.md every time `git commit` is run.
    Cross-platform: shell script on Linux/macOS, Python script on Windows.
    """
    git_dir = root / ".git"
    if not git_dir.is_dir():
        print("  [SKIP]  Not a git repo — skipping hook install.")
        return

    hooks_dir = git_dir / "hooks"
    hooks_dir.mkdir(exist_ok=True)
    hook_path = hooks_dir / "post-commit"

    python_exe = sys.executable  # full path to current Python interpreter
    state_abs = str((root / state_rel).resolve()).replace("\\", "/")  # forward slashes

    if OS_NAME == "Windows":
        # On Windows, git uses sh.exe bundled with Git for Windows.
        # We write a shell script that calls Python explicitly.
        hook_content = f"""#!/bin/sh
# ClawSync auto-sync git hook (post-commit)
MSG=$(git log -1 --pretty=%B | head -1)
FILES=$(git diff-tree --no-commit-id -r --name-only HEAD | tr '\\n' ', ' | sed 's/, $//')
TIMESTAMP=$(date '+%Y-%m-%d %H:%M:%S')
ROW="| $TIMESTAMP | Git/Commit | Commit: $MSG — files: $FILES |"
MARKER="<!-- ClawSync appends entries below this line. Most recent = bottom. -->"
python -c "
import sys
p='{state_abs}'
try:
    c=open(p,encoding='utf-8').read()
    r=sys.argv[1]
    m=sys.argv[2]
    if m in c: c=c.replace(m,m+'\\n'+r)
    else: c=c.rstrip()+'\\n\\n'+r+'\\n'
    open(p,'w',encoding='utf-8').write(c)
except Exception as e: print('[ClawSync hook] Error:',e)
" "$ROW" "$MARKER"
"""
    else:
        # Linux / macOS — pure shell, no Python dependency
        hook_content = f"""#!/bin/sh
# ClawSync auto-sync git hook (post-commit)
# Auto-generated by clawsync_init.py — do not edit manually.

STATE_FILE="{state_abs}"
MARKER="<!-- ClawSync appends entries below this line. Most recent = bottom. -->"

if [ ! -f "$STATE_FILE" ]; then
  exit 0
fi

MSG=$(git log -1 --pretty=%B 2>/dev/null | head -1)
FILES=$(git diff-tree --no-commit-id -r --name-only HEAD 2>/dev/null | tr '\n' ',' | sed 's/,$//' | sed 's/,/, /g')
TIMESTAMP=$(date '+%Y-%m-%d %H:%M:%S')
ROW="| $TIMESTAMP | Git/Commit | Commit: $MSG — files: $FILES |"

# Use Python to insert after the marker (handles multiline files safely)
{python_exe} - <<'PYEOF'
import sys
state = "{state_abs}"
marker = "<!-- ClawSync appends entries below this line. Most recent = bottom. -->"
try:
    with open(state, encoding='utf-8') as f:
        content = f.read()
except FileNotFoundError:
    sys.exit(0)

import subprocess, datetime
msg = subprocess.check_output(['git','log','-1','--pretty=%B'], text=True).splitlines()[0]
files_raw = subprocess.check_output(
    ['git','diff-tree','--no-commit-id','-r','--name-only','HEAD'], text=True
).strip().replace('\n', ', ')
ts = datetime.datetime.now().strftime('%Y-%m-%d %H:%M:%S')
row = f"| {{ts}} | Git/Commit | Commit: {{msg}} — files: {{files_raw}} |"

if marker in content:
    content = content.replace(marker, marker + '\n' + row)
else:
    content = content.rstrip() + '\n\n' + row + '\n'

with open(state, 'w', encoding='utf-8') as f:
    f.write(content)
PYEOF
"""

    # Write hook and make executable
    hook_path.write_text(hook_content, encoding="utf-8")
    if OS_NAME != "Windows":
        hook_path.chmod(0o755)
    print(f"  [OK]    {hook_path}")
    print(f"          → Every 'git commit' will auto-log to {state_rel}")


# ────────────────────────────────────────────────────────────────────────────
# CLI entry point
# ────────────────────────────────────────────────────────────────────────────

if __name__ == "__main__":
    import argparse

    parser = argparse.ArgumentParser(
        description="ClawSync — Global Context Bridge Initialiser",
        formatter_class=argparse.RawDescriptionHelpFormatter,
    )
    parser.add_argument(
        "path",
        nargs="?",
        default=None,
        help="Project root directory (default: current directory)",
    )
    parser.add_argument(
        "--overwrite",
        action="store_true",
        help="Regenerate files even if they already exist",
    )
    args = parser.parse_args()
    init_project(args.path, overwrite=args.overwrite)
